config/routes.rb
Rails.application.routes.draw do
  get 'documentales/index'
  get 'documentales/new'
  get 'estrenos/index'
  get 'estrenos/new'
  get 'peliculas/index'
  get 'peliculas/new'
  post 'peliculas', to: 'peliculas#create'
  post 'estrenos', to: 'estrenos#create'
  post 'documentales', to: 'documentales#create'
  root 'peliculas#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documental.rb
class Documental < ApplicationRecord
	validates :name, presence: true
	validates :sypnosis, presence: true
	validates :director, presence: true
end

app/models/estreno.rb
class Estreno < ApplicationRecord
	validates :name, presence: true
	validates :sypnosis, presence: true
	validates :director, presence: true
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
	validates :name, presence: true
	validates :sypnosis, presence: true
	validates :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentales_controller.rb
class DocumentalesController < ApplicationController
	def index
		@documentales = Documental.all
	end

	def new
	end


	def new
		@documental = Documental.new
	end

	def create
		@documental = Documental.new(documental_params)
		if @documental.save
			redirect_to action: "index"
		else
			render :new, status: :unprocessable_entity
		end
	end

	private

	def documental_params
		params.require(:documental).permit(:name, :sypnosis, :director)
	end
end

app/controllers/estrenos_controller.rb
class EstrenosController < ApplicationController
 def index
  	@estrenos = Estreno.all
  end

  def new
  end


  def new
  	@estreno = Estreno.new
  end
 
  def create
  	@estreno = Estreno.new(estreno_params)
  	if @estreno.save
  		redirect_to action: "index"
  	else
  		render :new, status: :unprocessable_entity
  	end
  end

  private

  def estreno_params
  	params.require(:estreno).permit(:name, :sypnosis, :director)
  end

end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  def index
  	@peliculas = Pelicula.all
  end

  def new
  end


  def new
  	@pelicula = Pelicula.new
  end
 
  def create
  	@pelicula = Pelicula.new(pelicula_params)
  	if @pelicula.save
  		redirect_to action: "index"
  	else
  		render :new, status: :unprocessable_entity
  	end
  end

  private

  def pelicula_params
  	params.require(:pelicula).permit(:name, :sypnosis, :director)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentales_helper.rb
module DocumentalesHelper
end

app/helpers/estrenos_helper.rb
module EstrenosHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/views/documentales/index.html.erb
<h2 class="text-center text-uppercase underline mb-4">Documentales</h2>
<%= link_to("Nuevo", documentales_new_path, class:"btn btn-outline-dark rounded-0") %>
<div class="row mx-auto mt-4">
<% @documentales.each do |documental| %>
	<div class="col-10 col-md-6 col-lg-4 col-3 mb-3">
		<div class="card">
			<div class="card-header fs-4 fw-bold"><%= documental.name %></div>
			<div class="card-body">
				<h5 class="card-title">Director: <span class="badge bg-warning text-dark"><%= documental.director %></span></h5>
				<p><%= documental.sypnosis %></p>
			</div>
		</div>
	</div>
<% end %>
</div>

app/views/documentales/new.html.erb
<div class="row">
	<div class="col-6 mx-auto">
		<div class="card p-3 bg-dark bg-gradient text-warning">
			<%= form_with model: @documental, method: :post do |form| %>
			<div class="mb-3">
				<%= form.label :name, "Nombre" %>
				<%= form.text_field :name, class:"form-control", :required => true %>
			</div>
			<div class="mb-3">
				<%= form.label :director, "Director" %>
				<%= form.text_field :director, class:"form-control",:required => true %>
			</div>
			<div class="mb-3">
				<%= form.label :sypnosis, "Sipnosis" %>
				<%= form.text_area :sypnosis, class: "form-control",:required => true %>
			</div>

			<div>
				<%= form.submit "Crear Estreno", class: "btn btn-outline-warning rounded-0" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/estrenos/index.html.erb
<h2 class="text-center text-uppercase underline mb-4">Estrenos</h2>
<%= link_to("Nuevo", estrenos_new_path, class:"btn btn-outline-dark rounded-0") %>
<div class="row mx-auto mt-4">
<% @estrenos.each do |estreno| %>
	<div class="col-10 col-md-6 col-lg-4 col-3 mb-3">
		<div class="card">
			<div class="card-header fs-4 fw-bold"><%= estreno.name %></div>
			<div class="card-body">
				<h5 class="card-title">Director: <span class="badge bg-warning text-dark"><%= estreno.director %></span></h5>
				<p><%= estreno.sypnosis %></p>
			</div>
		</div>
	</div>
<% end %>
</div>

app/views/estrenos/new.html.erb
<div class="row">
	<div class="col-6 mx-auto">
		<div class="card p-3 bg-dark bg-gradient text-warning">
			<%= form_with model: @estreno, method: :post do |form| %>
			<div class="mb-3">
				<%= form.label :name, "Nombre" %>
				<%= form.text_field :name, class:"form-control", :required => true %>
			</div>
			<div class="mb-3">
				<%= form.label :director, "Director" %>
				<%= form.text_field :director, class:"form-control",:required => true %>
			</div>
			<div class="mb-3">
				<%= form.label :sypnosis, "Sipnosis" %>
				<%= form.text_area :sypnosis, class: "form-control",:required => true %>
			</div>

			<div>
				<%= form.submit "Crear Estreno", class: "btn btn-outline-warning rounded-0" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMoviesD3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "extras" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container my-4">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/peliculas/index.html.erb
<h2 class="text-center text-uppercase underline mb-4">Películas</h2>
<%= link_to("Nuevo", peliculas_new_path, class:"btn btn-outline-dark rounded-0") %>
<div class="row mx-auto mt-4">
<% @peliculas.each do |pelicula| %>
	<div class="col-10 col-md-6 col-lg-4 col-3 mb-3">
		<div class="card">
			<div class="card-header fs-4 fw-bold"><%= pelicula.name %></div>
			<div class="card-body">
				<h5 class="card-title">Director: <span class="badge bg-warning text-dark"><%= pelicula.director %></span></h5>
				<p><%= pelicula.sypnosis %></p>
			</div>
		</div>
	</div>
<% end %>
</div>

app/views/peliculas/new.html.erb
<div class="row">
	<div class="col-6 mx-auto">
		<div class="card p-3 bg-dark bg-gradient text-warning">
			<%= form_with model: @pelicula, method: :post do |form| %>
			<div class="mb-3">
				<%= form.label :name, "Nombre" %>
				<%= form.text_field :name, class:"form-control", :required => true %>
			</div>
			<div class="mb-3">
				<%= form.label :director, "Director" %>
				<%= form.text_field :director, class:"form-control",:required => true %>
			</div>
			<div class="mb-3">
				<%= form.label :sypnosis, "Sipnosis" %>
				<%= form.text_area :sypnosis, class: "form-control",:required => true %>
			</div>

			<div>
				<%= form.submit "Crear Estreno", class: "btn btn-outline-warning rounded-0" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-warning border-2 border-bottom border-dark shadow">
	<div class="container">
		<%= link_to "#", class: "navbar-brand" do %>
			<img src="https://raw.githubusercontent.com/EniDev911/assets/main/png/logo/logo_con_bg.png" height="40" />
		<% end %>
		<%= button_tag type: :button, 
			class: "navbar-toggler",
			data: { bs_toggle: "collapse", bs_target: "#mainNav"} do %>
				<%= tag.span class: "navbar-toggler-icon" %>
		<% end %>
		<div class="collapse navbar-collapse" id="mainNav">
			<div class="navbar-nav ms-auto fw-bold">
				<%= link_to "Peliculas", root_path, class: "nav-link" %>
				<%= link_to "Estrenos", estrenos_index_path, class: "nav-link" %>
				<%= link_to "Documentales", documentales_index_path, class: "nav-link" %>
			</div>
		</div>
	</div>
</nav>